#!/usr/bin/env perl

use strict;
use warnings;

use Document::TriPart;
use Path::Class;

my $dir = dir '.';
my @children = $dir->children;

my $document = Document::TriPart->read( \join "\n", sort @children );
$document->edit;

@children = map { file $_ } split m/\n/, $document->body;
my $zero_count = length scalar @children;

print "0_count: $zero_count\n";
print join "\n", @children, '';

print "Are you sure you want to do this?\n";
<STDIN>;

my $ii = 0;
for my $file (@children) {
    # TODO: Skip if file is the same name
    $file = $file->basename;
    my $suffix = $file;
    $suffix =~ s/^[\d-]*//g;
    my $prefix = sprintf "%02d", $ii;
    system "git mv $file $prefix-$suffix";
    $ii++
}
